// entry/src/main/ets/common/Constants.ets
export class Constants {
  static readonly SAMPLE_RATE: number = 16000;
  static readonly CHANNEL_COUNT: number = 1;
  static readonly BUFFER_SIZE: number = 1280;

  static readonly XFYUN_APP_ID: string = "8d199df8";
  static readonly XFYUN_API_KEY: string = "dafaf8072a1e3534f96ebdcbf1f5c3e4";
  static readonly XFYUN_API_SECRET: string = "Njc4NDQ3NzJkN2I1NTRkMDkwMjJmZjA2";
  static readonly XFYUN_ASR_HOST: string = "iat-api.xfyun.cn";
  static readonly XFYUN_ASR_URL: string = "wss://iat-api.xfyun.cn/v2/iat";
}